"""Initial migration

Revision ID: 986a9c2c5bb5
Revises: 
Create Date: 2024-12-18 18:22:22.803579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '986a9c2c5bb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_artists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'artist_id'),
    info={'bind_key': None}
    )
    op.create_table('user_genres',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'genre_id'),
    info={'bind_key': None}
    )
    op.drop_table('ErrorLog')
    op.drop_table('sysdiagrams')
    op.drop_table('BuildVersion')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('preferred_genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_genre', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))

    op.create_table('BuildVersion',
    sa.Column('SystemInformationID', mssql.TINYINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Database Version', sa.NVARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('VersionDate', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('ModifiedDate', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('SystemInformationID', name='PK__BuildVer__35E58ECAFE9A3648')
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61DF56FAA7')
    )
    op.create_table('ErrorLog',
    sa.Column('ErrorLogID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ErrorTime', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('UserName', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('ErrorNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ErrorSeverity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorState', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorProcedure', sa.NVARCHAR(length=126), autoincrement=False, nullable=True),
    sa.Column('ErrorLine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorMessage', sa.NVARCHAR(length=4000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ErrorLogID', name='PK_ErrorLog_ErrorLogID')
    )
    op.drop_table('user_genres')
    op.drop_table('user_artists')
    op.drop_table('genre')
    op.drop_table('artist')
    # ### end Alembic commands ###
